FROM python:3.10-slim

WORKDIR /app

COPY streamlit_app.py /app/streamlit_app.py
COPY requirements.txt /app/requirements.txt

RUN pip install --no-cache-dir -r requirements.txt

CMD ["streamlit", "run", "streamlit_app.py", "--server.port=8501", "--server.address=0.0.0.0"]
