version: "3.9"
services:
  db:
    image: postgres:16
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: tododb
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - app-net

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db
    networks:
      - app-net

  backend:
    build: ./backend
    container_name: backend
    depends_on:
      - db
    ports:
      - "8000:8000"
    networks:
      - app-net

  frontend:
    build: ./frontend
    container_name: streamlit
    ports:
      - "8501:8501"
    depends_on:
      - backend
    networks:
      - app-net

  portainer:
    image: portainer/portainer-ce
    container_name: portainer
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    networks:
      - app-net

volumes:
  db_data:
  portainer_data:

networks:
  app-net: