FROM python:3.9-slim

WORKDIR /app

# Installation des dépendances système
RUN apt-get update && apt-get install -y \
    gcc \
    && rm -rf /var/lib/apt/lists/*

# Copie des fichiers nécessaires
COPY requirements.txt .
COPY data_generator.py .

# Installation des dépendances Python
RUN pip install --no-cache-dir -r requirements.txt

# Commande par défaut
CMD ["python", "data_generator.py"]